In [6]:
import pandas as pd

# Read the first .tsv file
df1 = pd.read_csv('title.basics.tsv', sep='\t')

# Read the second .tsv file (after decompressing if needed)
df2 = pd.read_csv('title.episode.tsv', sep='\t')

In [9]:
df1.head(20)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Poor Pierrot,Pauvre Pierrot,0,1892,\N,5,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,Short
5,tt0000006,short,Chinese Opium Den,Chinese Opium Den,0,1894,\N,1,Short
6,tt0000007,short,Corbett and Courtney Before the Kinetograph,Corbett and Courtney Before the Kinetograph,0,1894,\N,1,"Short,Sport"
7,tt0000008,short,Edison Kinetoscopic Record of a Sneeze,Edison Kinetoscopic Record of a Sneeze,0,1894,\N,1,"Documentary,Short"
8,tt0000009,movie,Miss Jerry,Miss Jerry,0,1894,\N,45,Romance
9,tt0000010,short,Leaving the Factory,La sortie de l'usine Lumière à Lyon,0,1895,\N,1,"Documentary,Short"
10,tt0000011,short,Akrobatisches Potpourri,Akrobatisches Potpourri,0,1895,\N,1,"Documentary,Short"
11,tt0000012,short,The Arrival of a Train,L'arrivée d'un train à La Ciotat,0,1896,\N,1,"Documentary,Short"
12,tt0000013,short,The Photographical Congress Arrives in Lyon,Le débarquement du congrès de photographie à Lyon,0,1895,\N,1,"Documentary,Short"
13,tt0000014,short,The Waterer Watered,L'arroseur arrosé,0,1895,\N,1,"Comedy,Short"
14,tt0000015,short,Around a Cabin,Autour d'une cabine,0,1894,\N,2,"Animation,Comedy,Short"
15,tt0000016,short,Boat Leaving the Port,Barque sortant du port,0,1895,\N,1,"Documentary,Short"
16,tt0000017,short,Italienischer Bauerntanz,Italienischer Bauerntanz,0,1895,\N,1,"Documentary,Short"
17,tt0000018,short,Das boxende Känguruh,Das boxende Känguruh,0,1895,\N,1,"Short,Sport"
18,tt0000019,short,The Clown Barber,The Clown Barber,0,1898,\N,\N,"Comedy,Short"
19,tt0000020,short,The Derby 1895,The Derby 1895,0,1895,\N,1,"Documentary,Short,Sport"

In [10]:
df2.head(20)

       tconst parentTconst seasonNumber episodeNumber
0   tt0031458   tt32857063           \N            \N
1   tt0041951    tt0041038            1             9
2   tt0042816    tt0989125            1            17
3   tt0042889    tt0989125           \N            \N
4   tt0043426    tt0040051            3            42
5   tt0043631    tt0989125            2            16
6   tt0043693    tt0989125            2             8
7   tt0043710    tt0989125            3             3
8   tt0044093    tt0959862            1             6
9   tt0044668    tt0044243            2            16
10  tt0044901    tt0989125            3            46
11  tt0045519    tt0989125            4            11
12  tt0045960    tt0044284            2             3
13  tt0046135    tt0989125            4             5
14  tt0046150    tt0341798           \N            \N
15  tt0046855    tt0046643            1             4
16  tt0046864    tt0989125            5            20
17  tt0047810    tt0914702            3            36
18  tt0047852    tt0047745            1            15
19  tt0047858    tt0046637            2             9